sonar.projectKey=linhcnh-finaltest-devops
sonar.projectName=LinhCNH FinalTest DevOps
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
sonar.coverage.exclusions=tests/**,**/__init__.py
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
